Hometask
emilkoooFD/JS_Study-basic pull request #4
Opened 2024-09-03 08:46 UTC by emilkoooFD

2024-09-03 11:16 UTC, GitEsense requested changes

2024-09-03 11:16 UTC, GitEsense commented on 10-array-clean/main.js
> +console.log(filterArray(clean, 10, array))
Тут не совсем то, чего мы ждали, но в целом...

Вот для анализа и примера, функция, которая не трогает исходный массив

```js
const arr = [
    -200, -22, -52, 10, 22, 35, 44, 15, 3, 7, 37, 69, 82, 55, 65, 72, 18, 4, 92,
];

//  Функция фильтрации
function filterArray(array, fn) {
    const resultArray = [];
    for (let i = 0; i < array.length; i++) {
        const isDelete = fn(array[i]);
        if (!isDelete) {
            resultArray.push(array[i]);
        }
    }
    return resultArray;
}

// Функция условия удаления (вынесено отдельно для удобства чтения)
function canDelete(num) {
    return (
        (num > 2 && num < 5) ||
        num === 7 ||
        (num > 50 && num % 5 === 0) ||
        num % 4 === 0 ||
        num % 11 === 2
    );
}

const result = filterArray(arr, canDelete);
console.log(result);

```
Функция - паттерн для проверки числа и функция фильтрации, которая прогоняет по "результату" и возвращает результирующий массив, не трогая исходный

Ваша же функция не просто возвращает массив, но ссылку на массив, который уже "не будет прежним", если вывести в консоль

```js
console.log(array);
console.log(filterArray(clean, 10, array));
console.log(array);
```
Вы увидите, что исходный массив Вы изменили (а не надо так)

2024-09-03 11:16 UTC, GitEsense commented on 11-date-array/main.js
> +console.log(result)
А если я передам скажем 29 февраля 2023 года? (29.02.2024), либо в EN формате (02/29/2024) = которая будет валидна?
Необходима так же проверка:
1. Високосный год
2. Кол-во дней в месяце (в феврале не может быть более 28 дней (не високосный год) и не более 29 (високосный)
3. В апреле не может быть 31 день.
4. Разделитель точка или тире (`.`, `-`)  = это RU формат (ДД.ММ.ГГГГ), а вот `/` = это EN формат (ММ.ДД.ГГГГ), так вот и должны проверяться, т.е. 
29-02-2024 = 29.02.2024 = 02/29/2024 = true, 
29-02-2023 = 29.02.2023 = 02/29/2023 = false

2024-09-03 11:16 UTC, GitEsense commented on 12-luna/main.js
> +function filter(cardNumber) {
Вы должны парсинг провести в рамках функции "luna", т.е. в функцию luna приходит номер карты и там уже проверка, если хоть один NaN есть - мы не можем с этой картой работать, а то получается Вы соберёте карточку из случайного набора чисел, которые смогли преобразоваться, скажем `asd12-fdsf212-f232-h423` вернёт нам 12212232423 - это некорректный номер карты и это будет ошибка, мы не должны такую проверять

2024-09-03 12:40 UTC, emilkoooFD commented on 11-date-array/main.js
> +console.log(result)
в условиях написано что 
Форматы дат: DD.MM.YY или MM/DD/YY.
День не может быть больше 31.
Месяц не может быть больше 12.
Учитывать високосные года для февраля (опционально).

2024-09-04 11:48 UTC, GitEsense requested changes
функцию luna необходимо исправить
Переменная correctNum нигде не фигурирует, вся работа идёт внутри функции luna и отвечает либо true, либо false и если "NaN" - можно вернуть NaN (по желанию)

2024-09-04 11:48 UTC, GitEsense commented on 11-date-array/main.js
> +console.log(result)
оставлю для анализа

```js
const length = 30;

function randomNumber(min = 1, max = 35) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}
const inputDates = Array.from({ length }, () => {
    const factor = Math.random() > 0.5 ? '/' : '-';

    const dateArray = [
        factor === '-' ? randomNumber() : randomNumber(0, 15),
        factor === '-' ? randomNumber(0, 15) : randomNumber(),
        randomNumber(1900, 2050),
    ].map((x) => x.toString().padStart(2, '0'));
    return dateArray.join(factor);
}).concat(Array.from({ length: 10 }, () => [randomNumber(28, 32), '02', randomNumber(1900, 2050)].join('-')));

function getDates(array, fn) {
    return array.map(stringToArray).filter(fn).sort(sortDatePattern).map(formatDate);
}

function formatDate(array) {
    return array.map(String).map((x, i) => (i === 2 ? x.padStart(4, '0') : x.padStart(2, '0'))).join('-');
}

function sortDatePattern(a, b) {
    let day, month, year;

    [day, month, year] = a;
    const dt1 = new Date(year, month - 1, day).getTime();

    [day, month, year] = b;
    const dt2 = new Date(year, month - 1, day).getTime();

    return dt1 - dt2;
}

function stringToArray(str) {
    let day, month, year;
    if (str.includes('/')) {
        [month, day, year] = str.split('/').map(x => parseInt(x));
    } else if (str.includes('-')) {
        [day, month, year] = str.split('-').map(x => parseInt(x));
    }

    if (!year || isNaN(day) || isNaN(month) || isNaN(year)) {
        return null;
    }
    return [day, month, year];
}

function checkCorrectDate(array) {
    if (array === null) {
        return false;
    }

    const [day, month, year] = array

    const LONG_MONTH_ARRAY = [1, 3, 5, 7, 8, 10, 12];

    const isLeapYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;

    // check month
    if (month < 1 || month > 12 || year <= 0) {
        return false;
    }

    // check day
    if (day < 1 || day > 31) {
        return false;
    }

    if (day === 31 && !LONG_MONTH_ARRAY.includes(month)) {
        return false;
    }

    // check February for correct day and leap year
    if (month === 2 && ((day === 29 && !isLeapYear) || day > 29)) {
        return false;
    }
    return true;
}

const res = getDates(inputDates, checkCorrectDate);
console.log(inputDates);
console.log(res);
```

2024-09-04 11:48 UTC, GitEsense commented on 12-luna/main.js
>  console.log(luna(correctNum))
Что-то я не понимаю как Вы работаете с номерами карты, которые приходят в функцию luna
Вы берёте "валидацию" во внешней среде и формируете там номер карты, при этом в функцию передаёте уже её, но в функции так же обращаетесь к "внешней" переменной, а не внутри функции и если я передам в функцию номер карты - я не получу ответа, но получу ошибку.

Давайте так...
заставьте выдать ответ от следующих значений и выглядеть оно будет так
```js
const card = '234s834503458353';
const card1 = '2342834503458353';
const card2 = '4561-2612-1234-5464';
const card3 = '4561-2612-1534-5464';

console.log(luna(card));  // NaN
console.log(luna(card1)); // true
console.log(luna(card2)); // false
console.log(luna(card3)); // true
```

2024-09-04 13:36 UTC, GitEsense approved these changes

2024-09-04 13:36 UTC, GitEsense commented on 12-luna/main.js
> +  }
но ведь карта может иметь не 16 знаков (теоретически), если Вы ознакомились с алгоритмом Луна - там об этом сказано, но в целом "ладно"

Вот просто и лаконично, оставляю для изучения:
```js
function cardLunaValidate(card) {
    const cardNumber = card
        .replaceAll('-', '')
        .split('')
        .map((x) => Number(x));
    if (cardNumber.includes(NaN)) {
        return NaN;
    }
    const isEven = (cardNumber.length - 1) % 2 === 0;

    for (let i = Number(isEven); i < cardNumber.length; i = i + 2) {
        cardNumber[i] =
            cardNumber[i] * 2 > 9 ? cardNumber[i] * 2 - 9 : cardNumber[i] * 2;
    }
    const sum = cardNumber.reduce((total, el) => total + el);
    return sum % 10 === 0;
}
const card = '234s834503458353';
const card1 = '2342834503458353';
const card2 = '4561-2612-1234-5464';
const card3 = '4561-2612-1534-5464';

function resultTemplate(card) {
    const startString = `Карта с номером: ${card}`;
    const endString = `получила результат: ${cardLunaValidate(card)}`;
    return `${startString} ${endString}`;
}
console.log(resultTemplate(card));
console.log(resultTemplate(card1));
console.log(resultTemplate(card2));
console.log(resultTemplate(card3));
```

2024-09-04 13:39 UTC, emilkoooFD commented on 12-luna/main.js
> +  }
Да-да, я читал, но там конкретно не было написано сколько может быть, было только то что если четное кол-во нужно начинать с нечетных чисел умножение, а если нечетное то четные числа умножать

2024-09-04 13:47 UTC, merged